#Working solution from internet
# version: "3.9"
# services:
#   postgres:
#     image: postgres:14-alpine
#     ports:
#       - 5432:5432
#     volumes:
#       - ~/apps/postgres:/var/lib/postgresql/data
#     environment:
#       - POSTGRES_PASSWORD=postgrespw
#       - POSTGRES_USER=postgres
#       - POSTGRES_DB=auctions

#From tutorial author

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgrespw
    volumes:
      - /var/lib/postgresql/data
      #- pgdata:/var/lib/postgresql/data
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    volumes:
      - /var/lib/mongodb/data # removed the named volume just using the filesystem
      #- mongodata:/var/lib/mongodb/data
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
# volumes:
#     pgdata:
#     mongodata:
    
